#import "./FungibleAssetBalanceFields.graphql"
#import "./FungibleAssetMetadataFields.graphql"
#import "./VaultInfoFields.graphql"

fragment SCMDPositionFields on scmd_position_current {
  position
  owner
  market
  collateral
  status
  collateral_asset_balance {
    ...FungibleAssetBalanceFields
  }
  market_info {
    ...BorrowMarketFields
  }
  debt_stores {
    debt_store
    vault
    debt_asset_balance {
      ...FungibleAssetBalanceFields
    }
    # vault_info {
    #   ...VaultInfoFields
    # }
  }
}
